import PopupEnquiry from "@/components/molecules/PopupEnquiry";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({
    subsets: ["latin"],
    display: "swap",
    weight: ["300", "400", "500", "600", "700", "800"],
    variable: "--font-open-sans",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    minimalUI: true,
    // Also supported by less commonly used
    // interactiveWidget: 'resizes-visual',
};

export default function MainLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    "h-screen flex flex-col font-openSans w-screen overflow-hidden ",
                    open_sans.variable
                )}
            >
                <div className="flex relative w-full flex-1 flex-col">
                    {children}
                    <PopupEnquiry />
                </div>
                <Toaster richColors />
            </body>
        </html>
    );
}
