import { cn } from '@/lib/utils';
import localFont from 'next/font/local';
import React from 'react'
import "./globals.css";
import Navbar from '@/components/organism/Navbar';

const galanoGrotesque = localFont({
    src: [
        {
            path: "./fonts/GalanoGrotesqueAltMedium.otf",
            weight: "500",
            style: "normal"
        },
        {
            path: "./fonts/GalanoGrotesqueAltMediumItalic.otf",
            weight: "500",
            style: "italic"
        },
        {
            path: "./fonts/GalanoGrotesqueRegular.otf",
            weight: "400",
            style: "normal"
        },
        {
            path: "./fonts/GalanoGrotesqueAltBold.otf",
            weight: "700",
            style: "normal"
        },
        {
            path: "./fonts/GalanoGrotesqueAltBoldItalic.otf",
            weight: "700",
            style: "italic"
        }
    ],
    variable: "--font-galano-Grotesque-alt"
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en"
        >
            <body className={cn("h-dvh flex flex-col font-galanoGrotesque w-screen overflow-hidden", galanoGrotesque.variable)}>
                <div className="flex w-full flex-col overflow-y-auto overflow-x-hidden scrollbar">
                    <Navbar />
                    <main className="flex w-full flex-1 flex-col">
                        <div className="flex h-auto w-full flex-1 flex-col items-center justify-center overflow-y-auto">
                            {children}
                        </div>
                    </main>
                </div>
            </body>
        </html>
    );
}