import { cn } from '@/lib/utils';
import localFont from 'next/font/local';
import React from 'react'
import "./globals.css";
import Navbar from '@/components/organism/Navbar';

const galanoGrotesque = localFont({
    src: [
        {
            path: "./fonts/GalanoGrotesqueAltMedium.otf",
            weight: "500",
            style: "normal"
        },
        {
            path: "./fonts/GalanoGrotesqueAltMediumitalic.otf",
            weight: "500",
            style: "italic"
        },
        {
            path: "./fonts/GalanoGrotesqueRegular.otf",
            weight: "400",
            style: "normal"
        },
        {
            path: "./fonts/GalanoGrotesqueAltBold.otf",
            weight: "700",
            style: "normal"
        },
        {
            path: "./fonts/GalanoGrotesqueAltBoldItalic.otf",
            weight: "700",
            style: "italic"
        }
    ],
    variable: "--font-galano-Grotesque-alt"
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en"
        >
            <body className={cn("h-screen font-galanoGrotesque w-screen", galanoGrotesque.variable)}>
                <Navbar />
                <main className="flex relative w-full h-[calc(100%-65px)] pt-4">
                    <section className="flex flex-1 max-w-7xl mx-auto w-full">
                        {children}
                    </section>
                </main>
            </body>
        </html>
    );
}